[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"
  customer_id = "X"
  service = "multiplay_billing"

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false


[[outputs.file]]
  files = ["stdout", "/tmp/metrics.out"]
  data_format = "ubazzar"
  fieldpass = ["quantity", "start_time"]

[[outputs.mp_cloud_pubsub]]
  project = "my-project"
  topic = "my-topic"
  data_format = "ubazzar"
  vault_address = "http://127.0.0.1:8200"
  vault_role_id = "cdc88ffa-8963-805e-4b7b-0ae97c57c21b"
  vault_secret_id = "130d066c-2068-02de-1d9c-03b5f55a075f"

# Egress
[[inputs.net]]
  interfaces = ["wlp59s0"]
  fieldpass = ["bytes_sent"]

[[aggregators.basicstats]]
  period = "5s"
  drop_original = true
  stats = ["non_negative_diff", "diff", "start_time"]
  fieldpass = ["bytes_sent"]
  [aggregators.basicstats.tags]
    unit_of_measure = "net-eu-west-mb-egress"

[[processors.byteconvert]]
  field_src = "bytes_sent_diff"
  field_name = "quantity"
  format = "mb"
  namepass = ["net"]

##Ingress
[[inputs.net]]
  interfaces = ["wlp59s0"]
  fieldpass = ["bytes_recv"]

[[aggregators.basicstats]]
  period = "5s"
  drop_original = true
  stats = ["diff", "start_time"]
  fieldpass = ["bytes_recv"]
  [aggregators.basicstats.tags]
    unit_of_measure = "net-eu-west-mb-ingress"


[[processors.byteconvert]]
  field_src = "bytes_recv_diff"
  field_name = "quantity"
  format = "mb"
  namepass = ["net"]
